### ISSUE TITLE
Create cli recovery

### ISSUE THREAD

**Issue by laniku** [dahliaOS/system_recovery#1]
not really an issue but an idea.

Create a cli based recovery just in case xserver breaks and we cn acsess the gui recovery.

**Comment by nmcain** [comment]
Well, this runs out of a seperate stateless system with it's own kernel,
but by tapping the reboot menu, and then selecting command line mode, you
can access the full suite of recovery tools.

**Comment by laniku** [comment]
ok, closing issue
